spring.application.name=ProgressoFit
server.port=8090

# Conexão com PostgreSQL do Docker
#spring.datasource.url=jdbc:postgresql://localhost:5433/progressofit-db
#spring.datasource.username=postgres
#spring.datasource.password=postgres

# Conexão com PostgreSQL do Render
spring.datasource.url=jdbc:postgresql://dpg-d3v0mamr433s73chvlsg-a.ohio-postgres.render.com/progressofit_db_qxn8
spring.datasource.username=progressofit_db_qxn8_user
spring.datasource.password=UQijJGdTCqkHCp1pBqeLDgCdN0m6VmjY

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT_SECRET:secret-padrao}